[display]
offset_x = 0
offset_y = 0
width = 1920
height = 1080

# dark-to-light order
[colors]
game_window=[34, 164, 243]
billboard=[193, 202, 215]
text=[1, 69, 135]
pizza_crust=[198, 134, 0]
pizza_base=[244, 203, 147]
pizza_sauce=[255, 77, 0]
hot_sauce=[[204, 0, 0], [255, 0, 0]]
# hot_sauce=[255, 0, 0]
choc_sauce=[68, 0, 0]
pink_sauce=[246, 102, 188]

[topping_ids]
seaweed = 1
shrimp = 2
squid = 3
dish = 3
fish = 4
supreme = [1,2,3,4]
liquorice = 1
chip = 2
marshmallow = 3
jelly = 4
bean = 4
sugar = [1,2,3,4]
sauce_keywords = ["spicy", "hot", "flamethrower", "pink"]