[display]
offset_x = 0
offset_y = 0
width = 1920
height = 1080

[colors]
game_window=[34, 164, 243]
billboard=[193, 202, 215]
pizza_base=[[119,69,0], [199,134,0]]
# pizza_base=[[119,69,0], [216,152,18]]
pizza_sauce=[255, 77, 0]
hot_sauce=[255, 0, 0]
choc_sauce=[255, 204, 0]
pink_sauce=[246, 102, 188]

[toppings]
seaweed = 1
shrimp = 2
squid = 3
dish = 3
fish = 4
supreme = [1,2,3,4]
liquorice = 1
chip = 2
marshmallow = 3
jelly = 4
bean = 4
sugar = [1,2,3,4]
sauces = ["spicy", "hot", "flamethrower", "pink"]

[ocr]
seconds_before_read = 1